version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Containerfile
    container_name: prom-sample-app
    ports:
      - "8000:8000"
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Containerfile
    container_name: prom-sample-prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
