spring.application.name=java25-floci-s3-vectors
s3-vectors.endpoint=${S3_VECTORS_ENDPOINT:http://localhost:4566}
s3-vectors.region=${AWS_REGION:us-east-1}
s3-vectors.access-key=${AWS_ACCESS_KEY_ID:test}
s3-vectors.secret-key=${AWS_SECRET_ACCESS_KEY:test}
s3-vectors.bucket-name=${S3_VECTORS_BUCKET:product-vectors}
s3-vectors.index-name=${S3_VECTORS_INDEX:products}
s3-vectors.dimension=${S3_VECTORS_DIMENSION:3}
springdoc.swagger-ui.path=/swagger-ui.html
