default_agent: echoNavy_Agent
agents:
  echoNavy_Agent:
    name: echoNavy_Agent
    language: python
    node_version: null
    entrypoint: /Users/diegopacheco/git/diegopacheco/ai-playground/pocs/agentcore-fun/echoNavy/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /Users/diegopacheco/git/diegopacheco/ai-playground/pocs/agentcore-fun/echoNavy/src
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: null
      region: null
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_name: echoNavy_Memory
      event_expiry_days: 30
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: OPENAI_API_KEY
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
