version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
